In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
y = pd.read_csv("data/combined_microbiome/metadata.csv", index_col=0).drop(columns='sample_key.1')

/var/folders/h3/pwlyvdxs71v5yn4z60q6qlv40000gn/T/ipykernel_56605/3756819998.py:1: DtypeWarning: Columns (9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  y = pd.read_csv("data/combined_microbiome/metadata.csv", index_col=0).drop(columns='sample_key.1')

In [4]:
X = pd.read_csv("/Users/ming/Documents/GitHub/Microbiome_transformer/data/combined_microbiome/relative_abundance_species_proportions_wide.csv", index_col=0)

In [5]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (33442, 2817)
y shape: (33442, 15)

In [6]:
y.head()

,source,original_sample_key,sample_id,study_id,label,is_healthy,age,gender,country,body_site,age_years,sex,continent,group_id,split
sample_key,,,,,,,,,,,,,,,
cmd:MV_FEI1_t1Q14,cmd,MV_FEI1_t1Q14,MV_FEI1_t1Q14,AsnicarF_2017,Healthy,True,0.0,female,ITA,stool,NaN,NaN,NaN,cmd:AsnicarF_2017,val
cmd:MV_FEI2_t1Q14,cmd,MV_FEI2_t1Q14,MV_FEI2_t1Q14,AsnicarF_2017,Healthy,True,0.0,male,ITA,stool,NaN,NaN,NaN,cmd:AsnicarF_2017,val
cmd:MV_FEI3_t1Q14,cmd,MV_FEI3_t1Q14,MV_FEI3_t1Q14,AsnicarF_2017,Healthy,True,0.0,male,ITA,stool,NaN,NaN,NaN,cmd:AsnicarF_2017,val
cmd:MV_FEI4_t1Q14,cmd,MV_FEI4_t1Q14,MV_FEI4_t1Q14,AsnicarF_2017,Healthy,True,1.0,male,ITA,stool,NaN,NaN,NaN,cmd:AsnicarF_2017,val
cmd:MV_FEI4_t2Q15,cmd,MV_FEI4_t2Q15,MV_FEI4_t2Q15,AsnicarF_2017,Healthy,True,1.0,male,ITA,stool,NaN,NaN,NaN,cmd:AsnicarF_2017,val

In [7]:
X.head()

,s__Abelson_murine_leukemia_virus,s__Abiotrophia_defectiva,s__Abiotrophia_sp_HMSC24B09,s__Absiella_dolichum,s__Acetatifactor_muris,s__Acetivibrio_ethanolgignens,s__Acetobacter_fabarum,s__Acetobacter_orientalis,s__Acetobacter_unclassified,s__Acetomicrobium_flavidum,...,s__Yersinia_wautersii,s__Yokenella_regensburgei,s__Yokose_virus,s__Zaire_ebolavirus,s__Zantedeschia_mild_mosaic_virus,s__Zika_virus,s__Zymomonas_mobilis,s__[Collinsella]_massiliensis,s__candidate_division_TM7_single_cell_isolate_TM7b,s__candidate_division_TM7_single_cell_isolate_TM7c
sample_key,,,,,,,,,,,,,,,,,,,,,
cmd:MV_FEI1_t1Q14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cmd:MV_FEI2_t1Q14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cmd:MV_FEI3_t1Q14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cmd:MV_FEI4_t1Q14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cmd:MV_FEI4_t2Q15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0